version: '3.4'
services:
  ddb:
    container_name: x-bbs-ddb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
  backend:
    container_name: x-bbs-backend
    build:
      context: ..
      dockerfile: ./backend/.devcontainer/Dockerfile
    command: /bin/sh -c "while :; do sleep 10; done"
    ports:
      - 4002:4002
  frontend:
    container_name: x-bbs-frontend
    build:
      context: ..
      dockerfile: ./frontend/.devcontainer/Dockerfile
    command: /bin/sh -c "while :; do sleep 10; done"
    ports:
      - 5173:5173
